export const ADDRESS = "Địa chỉ";
export const ROLE_IN_SCHOOL = "Vai trò";
export const IDENTITY_CARD_NUMBER = "CCCD";
export const CLASS_ROOM = "Lớp";
export const PHONE_NUMBER = "Số điện thoai";
export const FULL_NAME = "Họ và Tên";
export const SIGN_IN_SUCCESSFULLY = "Bạn đã có tài khoản";
export const HAVE_NO_ACCOUNT_FOUND = "Chào mừng bạn đến với BookHive";
export const PASS = "Mật Khẩu";
export const RE_PASS = "Nhập lại mật Khẩu";
export const REGISTER = "Đăng ký";
export const ALREADY_HAVE_ACCOUNT = "Đã có tài khoản?";
export const LOGIN = "Đăng nhập";
export const USE_AS_GUEST = "Sử dụng không cần đăng nhập";
export const BOTH_STUDENTS_N_TEACHERS = "Cho cả học sinh và giáo viên";
export const SIGN_IN_WITH_GOOGLE = "Đăng ký với Google";
export const NEXT = "Tiếp tục";
export const DASHBOARD = "Bảng điều khiển";
export const BORROW = "Mượn sách";
export const MEMBER = "Thành viên";
export const RESOURCE = "Tài nguyên";
export const SETTING = "Thiết lập";
export const LOGOUT = "Đăng xuất";
const appStrings =
				{
								TOTAL_BOOK: "Tổng số sách",
								borrow: {
												OVERDUE: "Quá hạn",
												USAGE_DATE_COUNT: "Ngày đọc",
												STATUS: "Trạng thái mượn",
												RETURNED: "Đã trả",
												LEFT: "Còn lại",
												DAY_LEFT: "Số ngày còn lại",
												BORROW_DATE: "Ngày mượn",
												RETURN_DATE: "Ngày trả", DUE_DATE: "Hạn trả",
												BOOK_DAMAGE_BEFORE_BORROW: "Tình trạng sách trước mượn",
												BOOK_DAMAGE_AFTER_BORROW: "Tình trạng sách sau mượn",
												BOOK_IMAGE_BEFORE_BORROW: "Hình ảnh sách trước khi mượn",
												BORROW_STATUS: "Trạng thái mượn",
												NO_BOOK_SELECTED: "Không có sách được chọn",
												EDIT_BOOK_SELECTED: "Sách mượn", CREATE_BORROWING: "Tạo lượt mượt",
								},
								BORROWED_BOOK: "Sách được mượn",
								OVERDUE: "Sách quá hạn",
								MEMBERS: "Thành viên",
								__: "",
								ADDRESS,
								ROLE_IN_SCHOOL,
								IDENTITY_CARD_NUMBER,
								CLASS_ROOM,
								PHONE_NUMBER,
								FULL_NAME,
								SIGN_IN_SUCCESSFULLY,
								HAVE_NO_ACCOUNT_FOUND,
								PASS,
								RE_PASS,
								REGISTER,
								ALREADY_HAVE_ACCOUNT,
								LOGIN,
								USE_AS_GUEST,
								BOTH_STUDENTS_N_TEACHERS,
								SIGN_IN_WITH_GOOGLE,
								NEXT,
								DASHBOARD,
								BORROW,
								MEMBER,
								RESOURCE,
								SETTING,
								LOGOUT, LOAN_RATE: "Lượt mượn sách",
								NUMBER_OF_BORROWED_BOOK: "Số lượng sách mượn (cuốn)",
								CANT_LOAD_LOAN_ANALYSIS_DATA: "Không thể tải được dữ liệu lượt mượn sách",
								CANT_LOAD_COUNT_ANALYSIS_DATA: "Không thể tải được dữ liệu thống kê hệ thống",
								CANT_LOAD_BOOK_QUANTITY_ANALYSIS_DATA: "Không thể tải được dữ liệu sách",
								NORMAL_BOOK: "Sách bình thường",
								NEW_BOOK: "Sách mới",
								DAMAGED_BOOK: "Sách bị hư hỏng",
								CATEGORY_ANALYZE_BY_LOAN: "Lượt mượn sách theo thể loại",
								TITLE: "Tiêu đề",
								RATINGS: "đánh giá",
								CATEGORY: "Thể loại",
								AVAILABILITY: "Bao gồm",
								STATUS: "Trạng thái", UNKNOWN: "Không biết",
								IN_SHELF: "Có sẵn trên kệ",
								CHECKED_OUT: "Đã được mượn",
								RESERVED: "Đã được đặt trước",
								LOST: "Bị thất lạc",
								DAMAGED: "Bị hỏng",
								PROCESSING: "Đang xử lý",
								ON_HOLD: "Tạm giữ",
								MISSING: "Mất tích",
								TRANSFERRED: "Đang chuyển đi",
								ARCHIVED: "Lưu trữ",
								unit: {
												BOOK: "cuốn",
												PEOPLE: "người",
												MEMBER: "thành viên",
												DAY: "ngày",
												ROW: "hàng",
												COL: "cột",
								},
								CHECKED_OUT__UNAVAILABLE: "Tạm hết",
								VERSION: "Phiên bản",
								ADD_AN_AUTHOR: "Thêm tác giả",
								WRITE_BY: "Được viết bởi",
								LIFE_SPAN: "Năm sinh - Năm mất(nếu có)",
								error: {
												REQUEST_ERROR: "Có lỗi xảy ra",
												AUTHOR_REQUEST_ERROR: "Không thể lấy thông tin tác giả",
												AUTHOR_EMPTY_ERROR: "Danh sách tác giả đang trống",
												EDIT_FAIL: "Chỉnh sửa thất bại",
												FAIL_TO_UPLOAD_EBOOK: "Tải file ebook lên thất bại",
												FAIL_TO_UPLOAD_AUDIO_BOOK: "Tải file audio lên thất bại",
												FAIL_TO_UPLOAD_COVER: "Tải file bìa sách lên thất bại",
												ADD_FAIL: "Thêm thất bại ",
												REMOVE_FAIL: "Xoá thất bại",
								},
								AUTHOR_NAME: "Tên tác giả",
								EDIT_AUTHOR: "Chỉnh sửa thông tin tác giả",
								SAVE: "Lưu",
								author: {
												EDIT_AUTHOR: "Chỉnh sửa thông tin tác giả",
												ADD_AN_AUTHOR: "Thêm tác giả",
												WRITE_BY: "Được viết bởi",
												LIFE_SPAN: "Năm sinh - Năm mất(nếu có)",
												properties: {
																AUTHOR_NAME: "Tên tác giả",
																AUTHOR_DESCRIPTION: "Mô tả",
																DEAD_DATE: "Ngày mất",
																BIRTHDATE: "Ngày sinh",
																DEAD_YEAR: "Năm mất",
																BIRTH_YEAR: "Năm sinh",
												},
												error: {
																ADD_FAILURE: "Thêm tác giả không thành công",
												},
												CHOOSE_AUTHORS: "Chọn tác giả", ADD_SUCCESS: "Thêm tác giả thành công",
								},
								book: {
												PHYSIC_BOOK: "Sách cứng",
												AVAILABILITY: "Sẵn có",
												POSITION: "Vị trí trên kệ",
												E_BOOK: "Sách điện tử",
												AUDIO_BOOK: "Sách nói",
												BOOK_COUNT: "Số lượng",
												NAME: "Tên sách",
												CODE: "Mã sách",
												ADD_BOOK: "Thêm sách",
												SEE_BOOK: "Quản lý kệ sách",
												OVERVIEW: "Tổng quan",
												EDITION: "Bản chỉnh sửa",
												DETAIL: "Chi tiết",
												REVIEW: "Đánh giá",
												LIST: "Bộ sách",
												RELATED: "Sách liên quan",
												SCAN_ISBN: "Quét mã ISBN",
												SCAN_COVER_IMAGE: "Quét bìa sách",
												NOT_BOOK_FOUND: "Không tìm thấy sách",
												CATEGORY: "Thể loại",
												PUBLISH_AT: "Xuất bản",
												PUBLISHER: "Nhà xuất bản",
												PAGE: "Trang",
												PAGE_COUNT: "Số trang",
												SERIES: "Bộ",
												HEIGHT: "Chiều dài",
												WIDTH: "Chiều rộng",
												THICKNESS: "Độ dày",
												WEIGHT: "Cân nặng",
												PRICE: "Giá",
												ISBN13: "Mã ISBN-13",
												ISBN10: "Mã ISBN-10",
												OTHER_IDENTIFIER: "Mã loại khác",
												LIBRARY_CODE: "Mã sách của thư viện",
												PHYSIC_DESCRIPTION: "Mô tả vật lý",
												SUGGESTION_CATEGORY: "Gợi ý",
												AVAILABLE_WITH: "Văn bản sẵn có với ngôn ngữ",
												E_BOOK_PREVIEW: "Bản xem trước file Epub",
												BOOK_CODE: "Mã sách",
												BOOK_IN_STORE: "Sách trong kho",
												BOOK_ON_SHELF: "Sách trên kệ",
												VERSION: "Phiên bản",
								},
								REMOVE: "Xoá",
								PDF_PREVIEW: "Đọc sách PDF",
								member: {
												BASE_INFO: "Thông tin cơ bản",
												BORROW_REQUEST: "Lượt mượn",
												READING: "Thống kê",
												HISTORY: "Lịch sử",
												CARD: "Thẻ",
												SETTING: "Tuỳ chọn",
												IDENTITY_CARD_NUMBER: "CCCD",
												ADD: "Thêm thành viên mới",
												FULLNAME: "Họ và tên",
												ROLE: "Vai trò",
												CLASSNAME: "Lớp",
												EMAIL: "Địa chỉ email",
												AVATAR: "Ảnh đại diện",
												PHONE: "Số điện thoại",
												CARD_NUMBER: "Thẻ thành viên", STATUS: "Trạng thái thành viên",
												VERIFIED: "Đã xác minh",
												NOT_VERIFIED: "Chưa xác minh",
												UPDATE: "Chỉnh sửa thông tin",
												BIRTH: "Ngày sinh",
												ADDRESS: "Địa chỉ",
												CARD_STATUS: "Trạng thái thẻ", CARD_EXPIRED_DATE: "Ngày hết hạn (thẻ)",
								},
								OTHER: "Khác",
								READING: "Đã đọc",
								CONTRIBUTION: "Đóng góp",
								SEE_PROFILE: "Xem profile",
								EMAIL: "Email",
								UPLOAD_IMAGE: "Tải ảnh lên",
								DOWNLOAD_IMAGE: "Tải ảnh xuống",
								NOTE: "Ghi chú",
								LIBRARY_ROOM: "Phòng sách",
								ADD_SHELF: "Thêm kệ",
								shelf: {
												ADD_SHELF: "Thêm kệ",
												COL_SIZE: "Số cột",
												ROW_SIZE: "Số hàng",
												NEW_SHELF: "Kệ mới",
												UN_LABEL: "Không có nhãn",
												SHELF_NAME: "Tên kệ",
												SHELF_LABEL: "Nhãn", ADD_ROW_ON_SHELF: "Thêm hàng sách", SHELF_EMPTY: "Kệ sách đang trống",
								},
								ACTION: "Hành động",
								EDIT: "Chỉnh sửa",
								CLOSE: "Đóng",
								warning: {
												YOU_NEED_TO_SAVE_FIRST: "Bạn cần lưu lại trước",
												CATEGORY_MIGHT_BE_DUPLICATED: "Thể loại bạn lưu mới có khả năng đã tồn tại. Bạn có thể lựa chọn thể loại" +
																" có sẵn hoặc tạo mới.",
												HAS_BOOK_ON_SHELF_ROW: "Kệ sách này đang chứa sách",
												DO_YOU_WANNA_DELETE: "Bạn có xác nhận muốn xoá",
												OUT_OF_RANGE: "Không thể thay đổi: Có sách đang nằm ngoài phạm vi mới.",
								},
								APPLY: "Áp dụng",
								success: {
												EDIT_SUCCESS: "Chỉnh sửa thành công",
												SAVE_SUCCESS: "Lưu thành công",
												DELETE_SUCCESS: "Xoá thành công",
								},
								SCAN_BAR_CODE: "Quét mã vạch",
								QUANTITY: "Số lượng",
								guide: {
												ADD_PHYSIC_BOOK_AVAILABILITY: "Với số lượng sách sẽ được tự động tạo và đánh dấu một mã định danh có cuốn" +
																" sách đó. Để hệ thống tự tạo mã bạn cần phải lưu thông tin đầu sách này vào hệ thống trước, sau khi" +
																" lưu thông tin, hệ thống ngay lập tức tạo cho bạn số lượng mã tương ứng với số lượng sách bạn nhập" +
																" và bạn cần phải dán mã sách này lên từng cuốn sách cứng mà trong kho có sẵn",
												NEW_CATEGORY_CHOSEN: "Chọn tick vào ô này đồng nghĩa với việc bạn chọn tạo 1 thể loại mới chưa có trong hệ thống",
												SUGGESTION_CATEGORY: "Đây là các thể laoij sách chúng tôi tìm được có thể khớp với thể loại bạn muốn thêm. Nếu bạn tìm thấy được thể loại trùng khớp với loại bạn muốn thêm mới, hãy chọn thay vì thêm mới.",
								},
								GUIDE: "Hướng dẫn",
								NOTICE: "Chú ý",
								LANGUAGE: "Ngôn ngữ",
								CONTINUE_WITHOUT_CHANGE: "Không thay đổi và tiếp tục",
								CONTINUE_WITH_CHANGE: "Thay đổi và tiếp tục",
								EPUB_PREVIEW: "Bản xem trước Epub",
								APP_NAME: "BÔK Hive",
								ADD: "Thêm",
								CONFIRM: "Xác nhận",
								CANCEL: "Huỷ",
								CANCELED_DELETE: "Đã huỷ thao tác xoá",
								GO_BACK: "Quay lại ",
								DESCRIPTION: "Mô tả ",
								NOTHING_CHANGE: "Không có dữ liệu thay đổi",
								RELOAD: "Tải lại", SYSTEM: "Hệ thống", GENERAL: "Tuỳ chọn chung", VIEW: "Xem",
				};
export default appStrings;

