import { Language, LanguageCode, LanguageCodeKey } from "@/helpers/appType";
import { createTheme } from "@mui/material/styles";
import { viVN } from '@mui/x-date-pickers/locales';

export const color = {
				PRIMARY: "#FA7C54",
				PRIMARY_20: "rgba(250,124,84,0.2)",
				PRIMARY_O10: "rgba(250,124,84,0.1)",
				SECONDARY: "#41B64D",
				COMFORT: "#41B64D",
				THIRD: "#F34040",
				LOVELY: "#F34040",
				SERIOUS: "#F34040",
				FOUR: "#926CFF",
				FOUR_20: "rgba(146,108,255,0.2)",
				FIFTH: "#EC6C9A",
				SIXTH: "#F09643",
				WARNING: "#F09643",
				BRIGHT_TEXT: "#FFFFFF",
				DARK_TEXT: "#4D4D4D",
				DARK: "#4D4D4D",
				DARK_LIGHTER_TEXT: "#ABABAB",
				DARK_BUT_LIGHTER: "#ABABAB",
				LIGHT_TEXT: "#FFFFFF",
				SHADOW: "rgba(44,42,46,0.39)",
				LIGHTER_SHADOW: "rgba(44,42,46,0.19)",
				PAGE_BACKGROUND: "#F3F3F7",
				WHITE: "#FFFFFF",
				CONCAVE_SHADOW: "#c8d0e7",
				CONCAVE_HIGHLIGHT: "#FFFFFF",
				CONCAVE_BACKGROUND: "#E4EBF5",
};
const languagesInVietnamese: LanguageCodeKey = {
				undefined: "undefined",
				en: "Tiếng Anh",
				vi: "Tiếng Việt",
				es: "Tiếng Tây Ban Nha",
				fr: "Tiếng Pháp",
				de: "Tiếng Đức",
				zh: "Tiếng Trung Quốc",
				ja: "Tiếng Nhật",
				ko: "Tiếng Hàn Quốc",
				ru: "Tiếng Nga",
				ar: "Tiếng Ả Rập",
				hi: "Tiếng Hindi",
				pt: "Tiếng Bồ Đào Nha",
				it: "Tiếng Ý",
				nl: "Tiếng Hà Lan",
				tr: "Tiếng Thổ Nhĩ Kỳ",
				pl: "Tiếng Ba Lan",
				uk: "Tiếng Ukraina",
				th: "Tiếng Thái",
				sv: "Tiếng Thụy Điển",
				id: "Tiếng Indonesia",
				fi: "Tiếng Phần Lan",
				no: "Tiếng Na Uy",
				da: "Tiếng Đan Mạch",
				he: "Tiếng Do Thái",
				el: "Tiếng Hy Lạp",
				hu: "Tiếng Hungary",
				ro: "Tiếng Romania",
				cs: "Tiếng Séc",
				sk: "Tiếng Slovakia",
				bg: "Tiếng Bulgaria",
				hr: "Tiếng Croatia",
				sr: "Tiếng Serbia",
				sl: "Tiếng Slovenia",
				ms: "Tiếng Malaysia",
				bn: "Tiếng Bengal",
				ta: "Tiếng Tamil",
				te: "Tiếng Telugu",
				kn: "Tiếng Kannada",
				ml: "Tiếng Malayalam",
				ur: "Tiếng Urdu",
				fa: "Tiếng Ba Tư",
				sw: "Tiếng Swahili",
				am: "Tiếng Amhara",
				yo: "Tiếng Yoruba",
				ig: "Tiếng Igbo",
				ha: "Tiếng Hausa",
				my: "Tiếng Myanmar",
				km: "Tiếng Khmer",
				lo: "Tiếng Lào",
				mn: "Tiếng Mông Cổ",
				si: "Tiếng Sinhala",
				uz: "Tiếng Uzbek",
				kk: "Tiếng Kazakh",
				az: "Tiếng Azerbaijan",
				hy: "Tiếng Armenia",
				ka: "Tiếng Gruzia",
				tg: "Tiếng Tajik",
				ky: "Tiếng Kyrgyz",
				ps: "Tiếng Pashto",
				sd: "Tiếng Sindhi",
				ne: "Tiếng Nepal",
				bo: "Tiếng Tây Tạng",
				dz: "Tiếng Dzongkha",
				gl: "Tiếng Galicia",
				eu: "Tiếng Basque",
				cy: "Tiếng Wales",
				ga: "Tiếng Ireland",
				mt: "Tiếng Malta",
				lb: "Tiếng Luxembourg",
				is: "Tiếng Iceland",
				af: "Tiếng Afrikaans",
				xh: "Tiếng Xhosa",
				zu: "Tiếng Zulu",
				st: "Tiếng Sotho",
				sn: "Tiếng Shona",
				nso: "Tiếng Sepedi",
				ts: "Tiếng Tsonga",
				ve: "Tiếng Venda",
				tn: "Tiếng Tswana",
};
export const language: LanguageCodeKey = {
				undefined: "unknown",
				en: "English",
				vi: "Tiếng Việt",
				es: "Español",
				fr: "Français",
				de: "Deutsch",
				zh: "中文",
				ja: "日本語",
				ko: "한국어",
				ru: "Русский",
				ar: "العربية",
				hi: "हिन्दी",
				pt: "Português",
				it: "Italiano",
				nl: "Nederlands",
				tr: "Türkçe",
				pl: "Polski",
				uk: "Українська",
				th: "ไทย",
				sv: "Svenska",
				id: "Bahasa Indonesia",
				fi: "Suomi",
				no: "Norsk",
				da: "Dansk",
				he: "עברית",
				el: "Ελληνικά",
				hu: "Magyar",
				ro: "Română",
				cs: "Čeština",
				sk: "Slovenčina",
				bg: "Български",
				hr: "Hrvatski",
				sr: "Српски",
				sl: "Slovenščina",
				ms: "Bahasa Melayu",
				bn: "বাংলা",
				ta: "தமிழ்",
				te: "తెలుగు",
				kn: "ಕನ್ನಡ",
				ml: "മലയാളം",
				ur: "اردو",
				fa: "فارسی",
				sw: "Kiswahili",
				am: "አማርኛ",
				yo: "Yorùbá",
				ig: "Igbo",
				ha: "Hausa",
				my: "မြန်မာစာ",
				km: "ភាសាខ្មែរ",
				lo: "ລາວ",
				mn: "Монгол",
				si: "සිංහල",
				uz: "Oʻzbek",
				kk: "Қазақша",
				az: "Azərbaycan",
				hy: "Հայերեն",
				ka: "ქართული",
				tg: "Тоҷикӣ",
				ky: "Кыргызча",
				ps: "پښتو",
				sd: "سنڌي",
				ne: "नेपाली",
				bo: "བོད་ཡིག",
				dz: "རྫོང་ཁ",
				gl: "Galego",
				eu: "Euskara",
				cy: "Cymraeg",
				ga: "Gaeilge",
				mt: "Malti",
				lb: "Lëtzebuergesch",
				is: "Íslenska",
				af: "Afrikaans",
				xh: "isiXhosa",
				zu: "isiZulu",
				st: "Sesotho",
				sn: "Shona",
				nso: "Sepedi",
				ts: "Xitsonga",
				ve: "Tshivenda",
				tn: "Setswana",
};
export const languages: Language[] = Object.entries( language ).map( ( [ code, name ] ) => ({
				code,
				name,
				langInVn: languagesInVietnamese[code as LanguageCode],
} as Language) );
export const theme = createTheme( {
				palette: {
								primary: {
												main: color.PRIMARY,
								},
								secondary: {
												main: color.SECONDARY,
								},
				},
				// colorSchemes: { light: true, dark: false },
				cssVariables: {
								colorSchemeSelector: 'data-toolpad-color-scheme',
				},
				typography: {
								subtitle1: { fontSize: 13, fontWeight: 'lighter' },
								h1: { fontSize: 35 },
								h2: { fontSize: 30 },
								h3: { fontSize: 25 },
								h4: { fontSize: 20 },
								h5: { fontSize: 14 },
								h6: { fontSize: 12 },
				},
				breakpoints: {
								values: {
												xs: 400,
												sm: 600,
												md: 900,
												lg: 1200,
												xl: 1536,
								},
				},
}, viVN );
