const a = {
				"shelves": [ {
								"id": 337666, "roomId": 1,
								"libraryRoom": null,
								"name": "Kệ mới 2",
								"label": "Không có nhãn",
								"column": "B",
								"row": "1",
								"x": 1, "y": 0, "rowShelves": [],
				}, {
								"id": 384491,
								"roomId": 1,
								"libraryRoom": null,
								"name": "Kệ mới 3",
								"label": "Không có nhãn",
								"column": "E",
								"row": "3",
								"x": 2,
								"y": 2,
								"rowShelves": [],
				}, {
								"id": 598191,
								"roomId": 1,
								"libraryRoom": null,
								"name": "Kệ mới 4",
								"label": "Không có nhãn",
								"column": "C",
								"row": "1", "x": 3, "y": 0,
								"rowShelves": [],
				}, {
								"id": 994601,
								"roomId": 1,
								"libraryRoom": null,
								"name": "Kệ mới 1",
								"label": "Không có nhãn",
								"column": "E",
								"row": "2",
								"x": 4,
								"y": 2,
								"rowShelves": [],
				} ],
				"columnSize": 6,
				"rowSize": 3,
};
